### ISSUE TITLE
Potential duty format cache incompatibility

### ISSUE THREAD

**Issue by Byron-Miles** [azurefireice/BuffDuty#11]
With version 1.5.0 the format of the duty list changed; however, the cache is not versioned, so it is possible that pre-1.5.0 duty list data could be returned from the cache and cause errors.

Suggestion: Add a 'version' value to the cache hash that can be changed in future builds to invalidate old data.

**Comment by azurefireice** [comment]
With version 1.6 the issue should be resolved. Thank you @Byron-Miles !!!
