### ISSUE TITLE
Title on multiple lines prevents loading

### ISSUE THREAD

**Issue by Byron-Miles** [azurefireice/BuffDuty#6]
https://github.com/azurefireice/BuffDuty/blob/c373e7ec32ce42defb2f3a20f202e5b75d72d385/BuffDuty.toc#L5

Having the Title: value over multiple line seems to prevent the addon from loading properly. The value is also missing a | (bar) at the start.

**Comment by azurefireice** [comment]
@Byron-Miles Cna you please show a screenshot? 
What does it mean `prevent the addon from loading properly`?

**Comment by azurefireice** [comment]
Oh gosh, you are right! Fixing it immediately

**Comment by azurefireice** [comment]
Fixed. Pls check [1.3.2 release ](https://www.curseforge.com/wow/addons/buff-duty/files/2903244)
