### ISSUE TITLE
Potential Version 2.0

### ISSUE THREAD

**Issue by Byron-Miles** [azurefireice/BuffDuty#8]
Hey, sorry I went quite on you, things got a bit busy (and sorry, not sure how else to reach you)... in my spare time I've been working on an updated version of BuffDuty for my own use and have re-worked / added a few features (overview below) that, as before, I thought you may be interested in.

Overview of major changes:
- Reworked logic to use an assignment list (instead of the 'order' list) that allows for both direct assignment - e.g. PlayerX=1,2 - and relative assignment with modifiers - e.g. PlayerY=own,x+1;[other]=lim>lim-1;*=<
- Modified duty printing to allow for multiple channels - e.g. r,c,w would post the duty list to raid, a custom channel, and whisper each assigned player
- Reworked console argument parsing to allow for the easy addition of commands, and added new commands for message customisation
- Added message customisation, including persistance via AceDB, with replacement macros - e.g. $name is replaced by the players name, $groups is replaced by their assigned groups

As it stands my code is basically a fork from version 1.3.2, so isn't directly mergable with version 1.4, but if it is to be taken forward I've been thinking of doing some refactoring anyway (e.g. adding a util.lua as you have in 1.4)

Regards,
Byron

**Comment by azurefireice** [comment]
Hey, Byron! 
I'm very excited to see your changes, they sound wonderful! 
What do you say if we sync up in Discord or any other messenger you like and see how we can merge it.
Just in case, my discord is `Azure#6690`.

**Comment by Byron-Miles** [comment]
Cool, I sent you a friend request in Discord.. should be from Takhisis
(Ariakas)
